name: Filing Buddy CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:

      - name: Build and deploy
        run: |
          cd ~/github/TaskFlow
          git pull origin main
          npm ci
          npm run build

          cd server
          npm ci
          cd ..
          pm2 reload ecosystem.config.js
